# Generated by Django 4.2.24 on 2025-09-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("status_change", "Status Change"),
                    ("assignment", "Assignment"),
                    ("work_done", "Work Done"),
                    ("view", "View"),
                ],
                max_length=32,
            ),
        ),
    ]
