# Generated by Django 4.2.24 on 2025-09-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_project_start_date_task_project_task_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="story_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
