# Generated by Django 4.2.24 on 2025-09-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_task_priority_task_story_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to="core.project",
            ),
        ),
    ]
